version: '3.3'

services:
  mediasoup:
    container_name: mediasoup
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./apps/Backend:/app
    environment:
      - NODE_ENV=development
    ports:
      - "4443:4443"  # HTTPS
      - "4444:4444"  # WebSocket
      - "40000-49999:40000-49999/udp"  # RTP ports
    command: npm start
    restart: unless-stopped