-- AlterTable
ALTER TABLE "Movie" ALTER COLUMN "adult" DROP NOT NULL,
ALTER COLUMN "backdrop_path" DROP NOT NULL,
ALTER COLUMN "original_language" DROP NOT NULL,
ALTER COLUMN "original_name" DROP NOT NULL,
ALTER COLUMN "overview" DROP NOT NULL,
ALTER COLUMN "popularity" DROP NOT NULL,
ALTER COLUMN "poster_path" DROP NOT NULL,
ALTER COLUMN "vote_average" DROP NOT NULL,
ALTER COLUMN "vote_count" DROP NOT NULL;
