name: Build and Deploy to Docker Hub

on: 
  push:
    branches:
      - main

jobs:         
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU (for multi-platform builds)
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build and Push Multi-Platform Docker Image
        uses: docker/build-push-action@v2
        with:
            context: ./Backend
            file: ./Backend/Dockerfile
            push: true
            platforms: linux/amd64,linux/arm64/v8
            tags: aryanrathore/watchalong_backend:latest
        
      - name: Deploy to Oracle Ec2
        uses: appleboy/ssh-action@master
        with: 
            host: ${{secrets.SSH_HOST}}
            username: ${{secrets.SSH_USERNAME}}
            key: ${{secrets.SSH_KEY}}
            script:  |
              sudo docker pull aryanrathore/watchalong_backend:latest
              sudo docker stop watchalong_backend || true
              sudo docker rm watchalong_backend || true
              sudo docker run -d -e DATABASE_URL=${{secrets.DB_URL}} --name watchalong_backend -p 3000:3000 aryanrathore/watchalong_backend:latest

     
        


